apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
  - secret.yaml
  - seed-job.yaml

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database
  app.kubernetes.io/part-of: ecommerce

# Made with Bob
